### PR TITLE
Stopping default recursor on debian based distros for sysvinit

### LINKED ISSUE #77: pdns_recursor_service_sysvinit behaves different when using Vagrant or Docker as providers
Our internal wrapper cookbook has been failing converge after 3.3.1 release.

The reason is that the `service` [block that stops](https://github.com/dnsimple/chef-pdns/blob/v3.4.0/resources/pdns_recursor_service_sysvinit.rb#L46-L49) the initial pdns-recursor service installed by the package itself behaves different in Vagrant and Docker as providers.

The following block part on pdns_recursor_service_sysvinit:

```
  service 'pdns-recursor' do
    supports restart: true, status: true
    action :disable
  end
```

- Effectively stop pdns-recursor and disables by running `update-rc.d`.
- Don't stop pdns-recursor but it disables by running `update-rc.d`

I have been able to reproduce this by simply running a recipe:

```
pdns_recursor_install 'instance' do
  action :install
end

pdns_recursor_config 'instance' do
   action :create
 end

pdns_recursor_service 'instance' do
   action [:enable, :start]
 end
```

And running it with Vagrant and Docker providers (using: `export KITCHEN_LOCAL_YAML=.kitchen.dokken.yml` for Docker).

Chef fails in Vagrant, but converges fine with Docker.

### PR DESCRIPTION
**Pull request by therobot**
This PR fixes #77 by solution proposed in the latest comment, (see issue for complete discussion of the bug).

The solution is stopping the default recursor instance only on debian based distros for sysvinit provider.

This has been proved to pass tests in both Vagrant and Docker.

### CODE REVIEW

File: resources/pdns_recursor_service_sysvinit.rb [hunk 1]
```diff
@@ -41,8 +41,17 @@
 
 
 action :enable do
-  # Some sysvint systems start the default pdns-recursor after installations
-  # We make sure to disable it which also stops the service in some platforms
+
+  # Some distros start pdns-recursor after installing it, we want to stop it
+  # The behavior of the init script on CentOS 6 causes a bug so we skip it there
+  # (see https://github.com/dnsimple/chef-pdns/issues/77#issuecomment-311644973)
+  service 'pdns-recursor' do
```
Comment (onlyhavecans) [inline resources/pdns_recursor_service_sysvinit.rb]: Duplicating the resource below is a chef 13 violation and will not work as desired in all cases. You will probably want to make an `pdns_default_actions` var and then set it based on the requirements and pass it to action on a single service.

Comment (therobot) [inline resources/pdns_recursor_service_sysvinit.rb]: Noted, thanks.

Comment (martinisoft) [inline resources/pdns_recursor_service_sysvinit.rb]: Cosigned about that. Resource cloning has been deprecated for some time in Chef, technically since just before Chef 11. While it is technically still supported via Chef 13, the side-affect is that you'll have the same resource being called multiple times in different ways which can make it unpredictable. See https://docs.chef.io/deprecations_resource_cloning.html about this behavior.

Comment (martinisoft) [inline resources/pdns_recursor_service_sysvinit.rb]: A way around this would be something like:

```ruby
pdns_recursor_actions = [:disable]
pdns_recursor_actions = pdns_recursor_actions.unshift(:stop) if node['platform_family'] == 'debian'

service 'pdns-recursor' do
    supports restart: true, status: true
    action pdns_recursor_actions
end
```

Comment (onlyhavecans) [inline resources/pdns_recursor_service_sysvinit.rb]: you can also use 
```
pdns_recursor_actions += [:stop] if node['platform_family'] == 'debian'
```
which is less rubyesque but I think looks cleaner

Comment (martinisoft) [inline resources/pdns_recursor_service_sysvinit.rb]: Since [order of array is a thing in chef](https://github.com/chef/chef/blob/master/lib/chef/runner.rb#L98) then that snippet may be an issue since the += appends. Hence my use of unshift to put stop first, not last.

Comment (martinisoft) [inline resources/pdns_recursor_service_sysvinit.rb]: You could simplify it by doing:

```ruby
pdns_recursor_actions = [:disable] if node['platform_family'] == 'debian'
(pdns_recursor_actions ||= []).push(:stop)
```

But that might be a little too obscure?
